export {default as Background} from './background.png';
export {default as FeedButton} from './FeedButtonDark.png';
export {default as LandingImage} from './landingTitle.png';
export {default as HomeTitle} from './MainTitle.png';
export {default as MintInfo} from './MintInfo.png';
export {default as HomeDiscordLogo} from './HomeDiscordLogo.png';
export {default as HomeTwitterLogo} from './HomeTwitterLogo.png';
export {default as CancelImage} from './cancel.png';
export {default as BaitImage} from './BaitImage.png'