export {default as Background} from './background.png';
export {default as MintBackground} from './mintBackground.png';
export {default as FeedButton} from './FeedButtonDark.png';
export {default as LandingImage} from './landingTitle.png';
export {default as HomeTitle} from './MainTitle.png';
export {default as MintInfo} from './MintInfo.png';
export {default as HomeDiscordLogo} from './HomeDiscordLogo.png';
export {default as HomeTwitterLogo} from './HomeTwitterLogo.png';
export {default as CancelImage} from './cancel.png';
export {default as BaitImage} from './BaitImage.png'
export { default as AllowGameButton} from './gameButton.png';
export { default as HomeBlurbImage} from './frenzy.png';
export { default as MetaMaskLogo} from './MetamaskLogo.png';
export { default as ConnectedMetaMask} from './connectedMetamask.png';
export { default as WalletConnectRemix} from './walletConnectRemix.png';
export { default as MintButtonImage} from './mintButtonImage.png';
export { default as ClaimButtonImage} from './claimImage.png';
export { default as FishingLicense} from './fishingLicense.gif';
export {default as ShirtImage} from './shirt.png';
export {default as SharkTankVideo} from './sharkTankVideo.mp4';
export {default as MinusImage} from './minus.png';
export {default as PlusImage} from './plus.png';